version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrodoc_web
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./config:/var/www/config
      - ./documentos_trab:/var/www/documentos_trab
      - ./docker/apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"  
    depends_on:
      - db
    networks:
      - agro_net

  db:
    image: mysql:8.0
    container_name: agrodoc_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root     
      MYSQL_DATABASE: bdagrodoc      
      MYSQL_USER: maria              
      MYSQL_PASSWORD: 1234           
    ports:
      - "3307:3306"  
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - agro_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: agrodoc_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - agro_net

networks:
  agro_net:
    driver: bridge
